"""
通用工具模块包

提供常用的工具类和函数，包括：
- config_yaml_parse: YAML 配置文件解析
- device_env_utils: 设备环境检测
- weight_file_utils: 模型权重保存加载
- file_dir_operate: 文件和目录操作
- time_datetime_utils: 时间日期工具
- encrypt_decrypt: 加密解密
- multi_thread_pool: 多线程/多进程池
"""

from .config_yaml_parse import (
    ConfigParser,
    load_config,
    save_config,
    merge_configs,
    create_config_template,
)

from .device_env_utils import (
    DeviceType,
    GPUInfo,
    MemoryInfo,
    DiskInfo,
    SystemInfo,
    DeviceInfo,
    DeviceManager,
    get_device,
    get_device_info,
    check_cuda_available,
    get_gpu_count,
    get_memory_info,
    get_disk_info,
    get_system_info,
    set_gpu_device,
    empty_cache,
    reset_peak_memory_stats,
)

from .weight_file_utils import (
    CheckpointMetadata,
    WeightFileUtils,
    CheckpointManager,
    WeightSharding,
    save_weights,
    load_weights,
    compute_file_hash,
    verify_weights_integrity,
    get_model_size,
    print_model_size,
)

from .file_dir_operate import (
    FileInfo,
    DirectoryTree,
    FileDirOperate,
    FileLock,
    file_lock,
    temporary_directory,
    temporary_file,
    ensure_dir,
    list_files,
    copy_file,
    move_file,
    delete_file,
    get_file_size,
    format_size,
    get_unique_filename,
)

from .time_datetime_utils import (
    TimeFormat,
    TimeRange,
    TimeDateUtils,
    Timer,
    now_str,
    today_str,
    timestamp,
    timestamp_seconds,
    get_date_range,
    format_time,
    parse_time,
    is_same_day,
    get_days_between,
)

from .encrypt_decrypt import (
    HashAlgorithm,
    CipherMode,
    KeyPair,
    EncryptedData,
    EncryptDecrypt,
    encrypt,
    decrypt,
    hash_string,
    hash_bytes,
    generate_password,
    secure_compare,
    encode_base64,
    decode_base64,
    encode_url_safe,
    decode_url_safe,
)

from .multi_thread_pool import (
    TaskStatus,
    TaskResult,
    PoolConfig,
    BaseExecutor,
    ThreadPoolExecutorHelper,
    ProcessPoolExecutorHelper,
    TaskQueue,
    WorkerPool,
    ProgressTracker,
    AsyncBatchExecutor,
    parallel_map,
    parallel_execute,
    batch_process,
    thread_pool_context,
    process_pool_context,
    executor,
)

__all__ = [
    # config_yaml_parse
    'ConfigParser',
    'load_config',
    'save_config',
    'merge_configs',
    'create_config_template',
    # device_env_utils
    'DeviceType',
    'GPUInfo',
    'MemoryInfo',
    'DiskInfo',
    'SystemInfo',
    'DeviceInfo',
    'DeviceManager',
    'get_device',
    'get_device_info',
    'check_cuda_available',
    'get_gpu_count',
    'get_memory_info',
    'get_disk_info',
    'get_system_info',
    'set_gpu_device',
    'empty_cache',
    'reset_peak_memory_stats',
    # weight_file_utils
    'CheckpointMetadata',
    'WeightFileUtils',
    'CheckpointManager',
    'WeightSharding',
    'save_weights',
    'load_weights',
    'compute_file_hash',
    'verify_weights_integrity',
    'get_model_size',
    'print_model_size',
    # file_dir_operate
    'FileInfo',
    'DirectoryTree',
    'FileDirOperate',
    'FileLock',
    'file_lock',
    'temporary_directory',
    'temporary_file',
    'ensure_dir',
    'list_files',
    'copy_file',
    'move_file',
    'delete_file',
    'get_file_size',
    'format_size',
    'get_unique_filename',
    # time_datetime_utils
    'TimeFormat',
    'TimeRange',
    'TimeDateUtils',
    'Timer',
    'now_str',
    'today_str',
    'timestamp',
    'timestamp_seconds',
    'get_date_range',
    'format_time',
    'parse_time',
    'is_same_day',
    'get_days_between',
    # encrypt_decrypt
    'HashAlgorithm',
    'CipherMode',
    'KeyPair',
    'EncryptedData',
    'EncryptDecrypt',
    'encrypt',
    'decrypt',
    'hash_string',
    'hash_bytes',
    'generate_password',
    'secure_compare',
    'encode_base64',
    'decode_base64',
    'encode_url_safe',
    'decode_url_safe',
    # multi_thread_pool
    'TaskStatus',
    'TaskResult',
    'PoolConfig',
    'BaseExecutor',
    'ThreadPoolExecutorHelper',
    'ProcessPoolExecutorHelper',
    'TaskQueue',
    'WorkerPool',
    'ProgressTracker',
    'AsyncBatchExecutor',
    'parallel_map',
    'parallel_execute',
    'batch_process',
    'thread_pool_context',
    'process_pool_context',
    'executor',
]
